version: 2.1
jobs:
  build:
    working_directory: ~/webapp
    docker:
      - image: circleci/openjdk:8-jdk
        environment:
        - MYSQL_ROOT_PASSWORD: Snehal100#
        - MYSQL_DATABASE: webapp
    steps:
      - checkout
      - run:
         name: Build WAR
         command: |
           echo 'This is the delivery pipeline'
           pwd
           ls -al
           ./mvnw clean install
           ./mvnw clean package
           ./mvnw clean test
